---
# tasks file for ngrok

- name: Install dependencies
  apt:
    state: present
    name: "{{ item }}"
    cache_valid_time: 3600
    update_cache: yes
  with_items:
      - unzip
      - apt-transport-https

- name: Download Ngrok
  unarchive:
    src: "{{ ngrok_download_url }}"
    dest: /usr/local/bin/
    remote_src: yes
    owner: root
    group: root
    mode: '0744'