---
# tasks file for ngrok

- name: Install dependencies
  apt:
    state: present
    name: "{{ item }}"
    cache_valid_time: 3600
    update_cache: yes
  with_items:
      - unzip
      - apt-transport-https
      - python-pip
      - python-dev
      - libffi-dev
      - libssl-dev

- name: Install python packages
  pip:
    state: present
    name: "{{ item }}"
  with_items:
    - urllib3
    - pyopenssl
    - ndg-httpsclient
    - pyasn1

- name: Download Ngrok
  get_url:
    url: "{{ ngrok_download_url }}"
    dest: "{{ ngrok_root_folder }}/ngrok.zip"

- name: Extract Ngrok
  unarchive:
    src: "{{ ngrok_root_folder }}/ngrok.zip"
    dest: "{{ ngrok_root_folder }}"
    remote_src: yes
    owner: root
    group: root
    mode: '0744'

- name: Symlink Ngrok in /usr/local/bin
  file:
    state: link
    src: "{{ ngrok_root_folder }}/ngrok"
    dest: /usr/local/bin/ngrok