---

libvirt_dns_server: 172.16.117.254
libvirt_dns_key: /etc/clefupdate.key
libvirt_dns_zone: dom117.u13.org

# Ip prefix used for newly created VMs
libvirt_ip_prefix: '172.16.117'
libvirt_bridge: br0
libvirt_user: root
