---
# tasks file for libvirt-provision

################################################################################
### Set dynamic variables
################################################################################

# Generate MAC addresses using SHA1 on VM name
# Output:
# {
#   "ubuntu-test": {
#     "mac": "42:4d:01"
# }
#
- name: Calculate MAC addresses for VMs
  set_fact:
    __libvirt_vm_macs: >
      { "{{ item.key }}": { "mac": "{{ libvirt_mac_prefix }}:{% for mac_part in (item.key | hash('sha1'))[-6:] | slice(3) %}{{ mac_part | join('') }}{{ '' if loop.last else ':' }}{% endfor %}" } }
  with_dict: "{{ libvirt_vms }}"

- name: Associate MAC address with VMs
  set_fact:
    libvirt_vms: "{{ libvirt_vms | combine(__libvirt_vm_macs, recursive=True) }}"

- name: Show the list of VMs
  debug:
    msg: "{{ libvirt_vms }}"
    verbosity: 2

################################################################################
### Install dependencies
################################################################################

- name: Install nsupdate python pip dependency
  pip:
    state: present
    name: dnspython

################################################################################
### Manage VMs
################################################################################

- include: create.yml
  when: libvirt_vm_state == 'create'

- include: delete.yml
  when: libvirt_vm_state == 'delete'

################################################################################
### Manage DNS entries
################################################################################

- include: dns.yml