---
# tasks file for libvirt

- name: Install nsupdate python pip dependency
  pip:
    state: present
    name: dnspython

- include: vm-create.yml
  when: libvirt_vm_state == 'create'

- include: vm-delete.yml
  when: libvirt_vm_state == 'delete'

