---
# tasks file for libvirt

- name: Define VM domains from XML templates
  virt:
    command: define
    name: "{{ item.1.name }}"
    xml: "{{ lookup('template', 'libvirt-vm-template.xml.j2') }}"
    uri: 'qemu:///system'
  with_indexed_items: "{{ libvirt_vms }}"

- name: Start VMs
  virt:
    command: start
    name: "{{ item.name }}"
    uri: 'qemu:///system'
  with_items: "{{ libvirt_vms }}"
