---
# tasks file for libvirt

- name: Gather the list of VM configured on the host
  virt:
    command: list_vms
  register: __libvirt_current_vms

# Clone only if the VM has not been already cloned
- name: "Clone the template VM into a new one"
  command: >
    virt-clone -o ubuntu0 -n {{ item.1.name }} -f /var/lib/libvirt/images/{{ item.1.name }}.qcow2 -m {{ '52:54:00:b9:d0:' ~ ('%02x' % item.0) }}
  when: item.1.name not in __libvirt_current_vms.list_vms
  with_indexed_items: "{{ libvirt_vms }}"

- name: Start VMs
  virt:
    command: start
    name: "{{ item.name }}"
    uri: 'qemu:///system'
  with_items: "{{ libvirt_vms }}"
