---
# tasks file for libvirt

- name: Install nsupdate python pip dependency
  pip:
    state: present
    name: dnspython

- name: Gather the list of VM
  virt:
    command: list_vms
  register: __libvirt_current_vms

- include: vm-create.yml
  when: libvirt_vm_state == 'create'

- include: vm-delete.yml
  when: libvirt_vm_state == 'delete'

