################################################################################
# > Playbook used to configure databases
#
# @author: <Your Name>
################################################################################
---

# TODO
- name: Configure databases
  hosts: databases
  become: yes

  roles:
    - role: common
      tags: ['common']

    - role: mysql
      tags: ['mysql']

    - role: webapp
      webapp_setup_enabled: no
      tags: ['webapp']

