################################################################################
# > Playbook used to configure blue/green master loadbalancer
#
# @author: Florian DAMBRINE <@Lowess>
################################################################################
---

- name: Configure blue/green master loadbalancer
  hosts: localhost
  become: yes

  vars_prompt:
    - name: "blue_green_master"
      prompt: "Which stack should be used as master? [blue, green]"
      private: no
      default: blue

  pre_tasks:
    - name: Check user input
      assert:
        that:
          - "blue_green_master in ['blue', 'green']"
        msg: 'The master stack should either be "blue" or "green"'

  roles:
    - role: blue-green
      tags: ['blue-green']
