################################################################################
# > Playbook used to configure webservers
#
# @author: <Your Name>
################################################################################
---

# TODO
- name: Configure webservers
  hosts: webservers
  become: yes

  roles:
    - role: common
      tags: ['common']

    - role: nginx
      tags: ['nginx']

    - role: uwsgi
      tags: ['uwsgi']

    - role: webapp
      tags: ['webapp']
